# Generated by Django 5.2.4 on 2025-07-19 06:38

import cloudinary_storage.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book',
            field=models.ImageField(default=django.utils.timezone.now, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='books/'),
            preserve_default=False,
        ),
    ]
