# Generated by Django 5.2.4 on 2025-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_books_user_alter_books_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
