# Generated by Django 5.2.4 on 2025-07-20 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_book_readinglist_readingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
